name             'awslogs-agent'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures awslogs-agent'
long_description 'Installs/Configures awslogs-agent'
version          '0.2.0'

supports 'ubuntu'
supports 'debian'
supports 'centos'
supports 'redhat'
depends 'poise-python', '~> 1.6.0'
depends 'apt'
